- name: run apt update
  ansible.builtin.apt:
    update_cache: true
- name: run apt upgrade
  ansible.builtin.apt:
    upgrade: true
- name: install python3-kubernetes client library
  ansible.builtin.apt:
    name: python3-kubernetes
  become: true
- name: create temporary kube-proxy config file for kubeadm init
  ansible.builtin.template:
    dest: /tmp/config.yaml
    src: config.yaml.j2
- name: run kubeadm init
  ansible.builtin.command:
    argv:
    - kubeadm
    - init
    - --config
    - /tmp/config.yaml
  register: kubeadm_init
- name: clean up temporary kube-proxy config file
  ansible.builtin.file:
    state: absent
    path: /tmp/config.yaml
- name: create ~/.kube directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
- name: copy kubernetes config to ~/.kube
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: '/home/{{ ansible_user }}/.kube/config'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'