- name: run apt update
  ansible.builtin.apt:
    update_cache: true
- name: run apt upgrade
  ansible.builtin.apt:
    upgrade: true
- name: install python3-kubernetes client library
  ansible.builtin.apt:
    name: python3-kubernetes
  become: true
- name: run kubeadm join
  ansible.builtin.command:
    cmd: >-
        {{ hostvars["vatomouro-0"].kubeadm_init.stdout_lines[-8] | trim(" \\") }}
        {{ hostvars["vatomouro-0"].kubeadm_init.stdout_lines[-7] | trim(" \\") }}
        {{ hostvars["vatomouro-0"].kubeadm_init.stdout_lines[-6] | trim }}
        --v=5
