# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize
# https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress
resources:
# Deploy the ingress controller
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v3.0.0/deployments/daemon-set/nginx-ingress.yaml
# Get access to the ingress controller
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v3.0.0/deployments/service/loadbalancer.yaml