apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-device-plugin
resources:
- namespace.yaml
helmCharts:
- name: nvidia-device-plugin
  includeCRDs: false
  namespace: nvidia-device-plugin
  releaseName: nvdp
  repo: https://nvidia.github.io/k8s-device-plugin
  version: 0.13.0