# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.3/manifests/install.yaml
  - server-nodeport.yaml
  - server-ingress.yaml
  # - server-certificate.yml
  # - repo-server-certificate.yml
  # - dex-server-certificate.yml