- name: check boot cmdline for cgroups settings
  shell: grep -c 'cgroups' /boot/cmdline.txt || true
  register: cmdline_cgroups
- name: add cgroups memory to boot cmdline
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    backrefs: yes
    regexp: '^(.*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
  when: cmdline_cgroups.stdout == '0'