dnsmasq_domain_needed: true
dnsmasq_bogus_priv: true
dnsmasq_expand_hosts: true
dnsmasq_domain: local
dnsmasq_addn_hosts: /etc/additional_hosts
dnsmasq_addn_hosts_list:
  - 192.168.1.90    zeph-control
  - 192.168.1.91    zeph-worker
  - 192.168.1.9     zephyrus
  - 192.168.1.100   raspberrypi-0
  - 192.168.1.101   raspberrypi-1
  - 192.168.1.102   raspberrypi-2
  - 192.168.1.103   raspberrypi-3
  # NOTE: IPs assigned depend on order of deployment
  - >
      192.168.1.192   argocd-server.k8s.local
      tekton-dashboard.k8s.local
      kubernetes-dashboard.k8s.local
  - 192.168.1.193   kubeflow-dashboard.k8s.local
