network:
  ethernets:
    eth0:
      dhcp4: false
      addresses: [IP_ADDRESS]
      nameservers:
        addresses: [192.168.1.100,8.8.8.8]
      routes:
        - to: default
          via: 192.168.1.1
