# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik
resources:
- namespace.yaml
# helm template --namespace=traefik traefik traefik/traefik --include-crds
- ingress-controller.yaml