# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- service.yaml
- deployment.yaml
- ingressclass.yaml
- dashboard-ingressroute.yaml