# https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner
resources:
  - namespace.yaml
  - class.yaml
  - deployment.yaml
  - rbac.yaml