apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jupyterhub
resources:
- namespace.yaml
helmCharts:
- name: jupyterhub
  includeCRDs: false
  namespace: jupyterhub
  releaseName: jupyterhub
  repo: https://jupyterhub.github.io/helm-chart
  version: 2.0.0
