- name: upgrade OS and install dnsmasq
  hosts: canary
  become: true
  roles:
  - dnsservers
- name: upgrade OS and configure resolvconf
  hosts:
  - raspi3s
  - k8sworkers
  become: true
  roles:
  - dnsclients