- name: upgrade OS and install dnsmasq
  hosts: canary
  become: true
  roles:
    - dnsservers
- name: configure DNS server
  hosts: k8s
  become: true
  tasks:
    - name: update /etc/resolv.conf
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf.head
        create: yes
        regexp: 'nameserver.*'
        line: 'nameserver 192.168.1.100'
