- name: upgrade OS and install dnsmasq
  hosts: canary
  become: true
  roles:
    - dnsservers
- name: configure DNS server
  hosts: k8s
  become: true
  tasks:
    - name: update /etc/resolv.conf
      ansible.builtin.copy:
        src: resolv.conf
        dest: /etc/resolv.conf
        mode: '0644'