pis:
  children:
    canary:
      hosts:
        raspberrypi-0:
          ansible_host: 192.168.1.100
    raspi3s:
      hosts:
        raspberrypi-0:
          ansible_host: 192.168.1.100
        raspberrypi-1:
          ansible_host: 192.168.1.101
        raspberrypi-2:
          ansible_host: 192.168.1.102
        raspberrypi-3:
          ansible_host: 192.168.1.103
    raspi4s:
      hosts:
        vatomouro-0:
          ansible_host: 192.168.1.110
        vatomouro-1:
          ansible_host: 192.168.1.111
        vatomouro-2:
          ansible_host: 192.168.1.112
        vatomouro-3:
          ansible_host: 192.168.1.113
    rockpis:
      hosts:
        vrachos-0:
          ansible_host: 192.168.1.120
        vrachos-1:
          ansible_host: 192.168.1.121
        vrachos-2:
          ansible_host: 192.168.1.122
        vrachos-3:
          ansible_host: 192.168.1.123
    k8scontrol:
      hosts:
        vatomouro-0:
          ansible_host: 192.168.1.110
    k8sworkers:
      hosts:
        vatomouro-1:
          ansible_host: 192.168.1.111
        vatomouro-2:
          ansible_host: 192.168.1.112
        vatomouro-3:
          ansible_host: 192.168.1.113
    k8s:
      children:
        k8scontrol:
        k8sworkers:
  vars:
    ansible_user: pi
