raspberrypis:
  children:
    canary:
      hosts:
        raspberrypi-0:
          ansible_host: 192.168.1.100
    k8s:
      hosts:
        raspberrypi-1:
          ansible_host: 192.168.1.101
        raspberrypi-2:
          ansible_host: 192.168.1.102
        raspberrypi-3:
          ansible_host: 192.168.1.103
  vars:
    ansible_user: pi
