pis:
  children:
    canary:
      hosts:
        raspberrypi-0:
          ansible_host: 192.168.1.100
    raspi3s:
      hosts:
        raspberrypi-0:
          ansible_host: 192.168.1.100
        raspberrypi-1:
          ansible_host: 192.168.1.101
        raspberrypi-2:
          ansible_host: 192.168.1.102
        raspberrypi-3:
          ansible_host: 192.168.1.103
    raspi4s:
      hosts:
        vatomouro-0:
          ansible_host: 192.168.1.110
        vatomouro-1:
          ansible_host: 192.168.1.111
        vatomouro-2:
          ansible_host: 192.168.1.112
        vatomouro-3:
          ansible_host: 192.168.1.113
    raspis:
      children:
        raspi3s:
        raspi4s:
    rockpis:
      hosts:
        vrachos-0:
          ansible_host: 192.168.1.120
        vrachos-1:
          ansible_host: 192.168.1.121
        vrachos-2:
          ansible_host: 192.168.1.122
        vrachos-3:
          ansible_host: 192.168.1.123
        vrachos-4:
          ansible_host: 192.168.1.124
        vrachos-5:
          ansible_host: 192.168.1.125
      vars:
        ansible_user: radxa
    k8scontrol:
      hosts:
        vatomouro-0:
          ansible_host: 192.168.1.110
        vatomouro-1:
          ansible_host: 192.168.1.111
        vatomouro-2:
          ansible_host: 192.168.1.112
    k8sworkers:
      hosts:
        vatomouro-3:
          ansible_host: 192.168.1.113
        vrachos-0:
          ansible_host: 192.168.1.120
        vrachos-1:
          ansible_host: 192.168.1.121
        vrachos-2:
          ansible_host: 192.168.1.122
    k8sstorage:
      hosts:
        vrachos-3:
          ansible_host: 192.168.1.123
        vrachos-4:
          ansible_host: 192.168.1.124
        vrachos-5:
          ansible_host: 192.168.1.125
    k8s:
      children:
        k8scontrol:
        k8sworkers:
        k8sstorage:
  vars:
    ansible_user: pi
    control_plane_endpoint: k8s.clunacy.dev
    apiserver_vip: 192.168.1.150
    pod_network_cidr: 10.90.0.0/16
    ip_address_pool_addresses: 192.168.1.192/27