- name: create kubernetes control plane with kubeadm
  hosts:
  - k8scontrol
  become: true
  tasks:
  - name: update self entry in /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '.*{{ inventory_hostname }}'
      line: '{{ ansible_default_ipv4.address }} {{ inventory_hostname }}'
  - name: run kubeadm reset
    ansible.builtin.command:
      cmd: kubeadm reset --force
  - name: reboot and await restart
    ansible.builtin.reboot:

  - name: run kubeadm init
    ansible.builtin.command:
      argv:
      - kubeadm
      - init
      - --control-plane-endpoint
      - '{{ control_plane_endpoint }}'
      - --pod-network-cidr
      - '{{ pod_network_cidr }}'
    register: kubeadm_init

- name: join workers to control plane with kubeadm
  hosts:
  # TODO: add rock pis
  - k8sworkers
  become: true
  tasks:
  - name: run kubeadm reset
    ansible.builtin.command:
      cmd: kubeadm reset --force
  - name: reboot and await restart
    ansible.builtin.reboot:

  - name: run kubeadm join
    ansible.builtin.command:
      cmd: >-
        {{ hostvars[control_plane_endpoint].kubeadm_init.stdout_lines[-2] | trim(" \\") }}
        {{ hostvars[control_plane_endpoint].kubeadm_init.stdout_lines[-1] | trim }}
