- name: upgrade OS and install nfs-kernel-server
  hosts: canary
  become: true
  roles:
    - nfsservers
- name: enable NFS client support
  hosts: k8s
  become: true
  tasks:
    - name: install nfs-common
      ansible.builtin.apt:
        name: nfs-common