- name: install nginx ingress controller
  hosts:
  - vatomouro-0
  tasks:
  - name: apply nginx-ingress as argocd application
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: nginx-ingress
          namespace: argocd
        spec:
          project: default
          source:
            repoURL: https://github.com/McClunatic/k8s-learning.git
            targetRevision: HEAD
            path: gitops/nginx-ingress/overlays/prod
          destination:
            name: in-cluster
            namespace: nginx-ingress
          syncPolicy:
            automated: {}