- name: install rook for cloud-native storage orchestration
  hosts:
  - vatomouro-0
  tasks:
  - name: apply rook-ceph as argocd application
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: rook
          namespace: argocd
        spec:
          project: default
          source:
            repoURL: https://github.com/McClunatic/k8s-learning.git
            targetRevision: HEAD
            path: gitops/rook/overlays/prod
          destination:
            name: in-cluster
            namespace: rook-ceph
          syncPolicy:
            automated: {}