- name: run apt update
  ansible.builtin.apt:
    update_cache: true
- name: run apt upgrade
  ansible.builtin.apt:
    upgrade: true
- name: update /etc/resolvconf.conf
  ansible.builtin.lineinfile:
    path: /etc/resolvconf.conf
    regexp: '\.*name_servers.*'
    line: 'name_servers=192.168.1.100'
- name: apply resolvconf configuration
  ansible.builtin.command: resolvconf -u
- name: create /run/systemd/resolve directory
  ansible.builtin.file:
    path: /run/systemd/resolve
    state: directory
    recurse: true
    mode: '0755'
- name: create symbolic link to /etc/resolv.conf
  ansible.builtin.file:
    src: /etc/resolv.conf
    dest: /run/systemd/resolve/resolv.conf
    state: link
