apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-staging
resources:
  - ../../base
patchesStrategicMerge:
  - application-controller.yaml
  - server-clusterrolebinding.yaml
  - server-ingress.yaml
  - server-service.yaml