# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.22.0/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.22.0/interceptors.yaml