# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.7.1