- name: run apt update
  ansible.builtin.apt:
    update_cache: true
- name: run apt upgrade
  ansible.builtin.apt:
    upgrade: true
- name: run apt install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
- name: configure dnsmasq
  ansible.builtin.template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.j2
    validate: dnsmasq --test -C %s
- name: add dnsmasq hosts
  when: dnsmasq_addn_hosts is defined
  ansible.builtin.template:
    dest: "{{ dnsmasq_addn_hosts }}"
    src: additional_hosts.j2
- name: restart service dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
