- name: run apt update
  ansible.builtin.apt:
    update_cache: true
- name: run apt upgrade
  ansible.builtin.apt:
    upgrade: true
- name: run apt install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
- name: configure dnsmasq
  ansible.builtin.template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.j2
    validate: dnsmasq --test -C %s
- name: add dnsmasq hosts
  when: dnsmasq_addn_hosts is defined
  ansible.builtin.template:
    dest: "{{ dnsmasq_addn_hosts }}"
    src: "{{ dnsmasq_addn_hosts_template }}"
- name: update self entry in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '\.*{{ inventory_hostname }}'
    line: '{{ ansible_default_ipv4.address }} {{ inventory_hostname }}'
- name: restart service dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
