apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: clunacy-pool
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  failureDomain: host
  replicated:
    size: 3
