apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/rook/rook/v1.11.5/deploy/examples/crds.yaml
- https://raw.githubusercontent.com/rook/rook/v1.11.5/deploy/examples/common.yaml
- https://raw.githubusercontent.com/rook/rook/v1.11.5/deploy/examples/operator.yaml
- https://raw.githubusercontent.com/rook/rook/v1.11.5/deploy/examples/cluster.yaml
- blockpool.yaml
- objectstore.yaml
- storageclass-block.yaml
- storageclass-object.yaml
patchesStrategicMerge:
- cluster-placement.yaml
- operator-config-affinity-tolerations.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: rook-ceph-operator
  path: operator-discover-tolerations-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: rook-ceph-operator
  path: operator-discover-affinity-patch.yaml