kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  CSI_PROVISIONER_NODE_AFFINITY: "node-role.kubernetes.io/storage=true"
  CSI_PROVISIONER_TOLERATIONS: |
    - effect: NoSchedule
      key: node-role.kubernetes.io/storage
      operator: Exists
  CSI_PLUGIN_NODE_AFFINITY: "node-role.kubernetes.io/storage=true"
  CSI_PLUGIN_TOLERATIONS: |
    - effect: NoSchedule
      key: node-role.kubernetes.io/storage
      operator: Exists
  ROOK_ENABLE_DISCOVERY_DAEMON: "true"